version: 2
updates:
  - package-ecosystem: "poetry"
    directory: "/webknossos"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "scikit-image"
  - package-ecosystem: "poetry"
    directory: "/docs"
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "poetry"
    directory: "/cluster_tools"
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "poetry"
    directory: "/wkcuber"
    ignore:
      - dependency-name: "*"