[tool.poetry]
name = "wk-libs-docs"
description = "Documentation for webknossos-libs"
version = "0.0.1"
authors = ["scalable minds <hello@scalableminds.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
LinkChecker = "^10.0.1"
mkdocs = "1.2.2"
mkdocs-material = "^7.3.0"
mkdocs-redirects = "^1.0.3"
pdoc = { git = "https://github.com/mitmproxy/pdoc.git", rev = "1574222ab0568e072dc04e3569027d39aa124256"}
webknossos = { path = "../webknossos/", develop = true }
wkcuber = { path = "../wkcuber/", develop = true }

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
