[tool.poetry]
name = "wk-libs-docs"
description = "Documentation for webknossos-libs"
version = "0.0.1"
authors = ["scalable minds <hello@scalableminds.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"

[tool.poetry.dev-dependencies]
LinkChecker = "^10.0.1"
mkdocs = "^1.3.0"
mkdocs-material = "^8.2.13"
mkdocs-redirects = "^1.0.3"
mkdocs-video = "^1.5.0"
pdoc = "^11.1.0"
webknossos = { path = "../webknossos/", develop = true }
wkcuber = { path = "../wkcuber/", develop = true }

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
